version: "3.7"

services:

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - "7788:3306"
    networks:
      - sqlx-network
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    networks:
      - sqlx-network
    ports:
      - "8877:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

networks:
  sqlx-network: